-- Make the audit hash chain verifiable.
--
-- Two defects, both invisible until something actually walked the chain.
--
-- 1. THE CHAIN FORKED. Each new event linked to the tail found by
--    `ORDER BY ts DESC` — the LATEST-DATED event, not the last-inserted one.
--    Any two events written out of timestamp order therefore linked to the same
--    predecessor, and the chain split in two. On this deployment it had forked in
--    hundreds of places. A forked chain proves nothing: a spliced-in row is
--    indistinguishable from an ordinary branch. `seq` gives insertion a real
--    order, which is the order the chain is actually built in.
--
-- 2. THE HASH COULD NOT BE RECOMPUTED. It was taken over Go values, but
--    verification can only see what Postgres stored, and the two are not the same
--    bytes: timestamptz keeps microseconds while Go keeps nanoseconds, and jsonb
--    re-orders object keys and drops whitespace. Every honest row failed to
--    reproduce its own hash. The writer now hashes values that survive the round
--    trip, and `hash_version` marks the rows where that is true.
--
-- Existing rows keep hash_version 1 and are reported as unverifiable rather than
-- as tampered with. Their hashes were computed over bytes that no longer exist,
-- and the log is append-only by design — there is nothing to rewrite them with,
-- and rewriting an audit log to make it verify would defeat the purpose.
ALTER TABLE audit_events
    ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN hash_version SMALLINT NOT NULL DEFAULT 1;

-- The chain is walked per organization in insertion order, and the tail is read
-- on every single write.
CREATE INDEX ix_audit_seq ON audit_events (organization_id, seq);
